name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Check Github env
        run: |
          echo GITHUB_SHA: $GITHUB_SHA
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.sha: ${{ github.sha }}

      - name: git log
        run: |
          git log -n 5

      - name: Check env
        run: |
          env
