name: Test

on:
  push:
  workflow_dispatch:

jobs:
  env:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Github env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.sha: ${{ github.sha }}
          echo github.event.before: ${{ github.event.before }}
          echo "$GITHUB_CONTEXT"
          pwd

      - name: git log
        run: |
          git log -n 5

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'json'
          filters: |
            any:
              - '**'

      - name: Show changes
        run: |
          echo ${{ steps.changes.outputs.any_files }}

  check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        problem: [pA, pB, pC]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make flags dir
        run: |
          mkdir -p /home/runner/flags/build-pdf/
          touch /home/runner/flags/build-pdf/.keep
          mkdir -p /home/runner/flags/build-tests/
          touch /home/runner/flags/build-tests/.keep

      - name: Set env
        id: env
        working-directory: ${{ matrix.problem }}
        run: |
          export model_solution=$(SOLUTIONS_JSON=./solutions.json python3 scripts/internal/get_model_solution.py)
          echo "::set-output name=model_solution::$model_solution"

      - run: |
          echo "${{ matrix.problem }}/solution/${{ steps.env.outputs.model_solution }}"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'json'
          filters: |
            pdf:
              - ${{ matrix.problem }}/statement/*.jpg
              - ${{ matrix.problem }}/statement/index.md
              - ${{ matrix.problem }}/problem.json
              - template.tex
            cover:
              - cover.tex
            input:
              - ${{ matrix.problem }}/gen/**
            output:
              - ${{ matrix.problem }}/solution/${{ steps.env.outputs.model_solution }}
            solutions:
              - ${{ matrix.problem }}/solution/**

      - name: Show changed files
        env:
          FILES: ${{ toJson(steps.changes.outputs) }}
        run: |
          echo "$FILES"

      - name: Check changed lines
        run: |
          git diff ${{ github.event.before }}..HEAD -U0 ${{ matrix.problem }}/problem.json | grep '"contest_name"\|"problem_label"\|"name"\|"title"\|"memory_limit"\|"time_limit"'
          if [ $? -eq 0 ]; then
            echo "Change for pdf";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 ${{ matrix.problem }}/problem.json | grep '"time_limit"'
          if [ $? -eq 0 ]; then
            echo "Change for time_limit";
          fi

      - name: Set problem flag
        if: steps.changes.outputs.pdf == 'true' || (matrix.problem == 'pA' && steps.changes.outputs.cover == 'true')
        run: |
          echo true > /home/runner/flags/build-pdf/${{ matrix.problem }}

      - name: Set tests flag
        if: steps.changes.outputs.input == 'true'
        run: |
          echo true > /home/runner/flags/build-tests/${{ matrix.problem }}

      - name: Upload flags
        uses: actions/upload-artifact@v2
        with:
          name: flags
          path: /home/runner/flags/

  check-post:
    needs: check
    runs-on: ubuntu-18.04
    outputs:
      build-pdf: ${{ steps.build-pdf.outputs.build-pdf }}
      build-tests: ${{ steps.build-tests.outputs.build-tests }}

    steps:
      - name: Download flags
        uses: actions/download-artifact@v2
        with:
          name: flags
          path: /home/runner/flags/

      - name: build-pdf
        id: build-pdf
        working-directory: /home/runner/flags/build-pdf/
        run: |
          probs=$(python3 -c 'import json, glob; print(json.dumps(glob.glob("*")))')
          echo $probs
          echo "::set-output name=build-pdf::$probs"

      - name: build-tests
        id: build-tests
        working-directory: /home/runner/flags/build-tests/
        run: |
          probs=$(python3 -c 'import json, glob; print(json.dumps(glob.glob("*")))')
          echo $probs
          echo "::set-output name=build-tests::$probs"

  build-pdf:
    if: needs.check-post.outputs.build-pdf != '[]'
    needs: check-post
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        problem: ${{ fromJson(needs.check-post.outputs.build-pdf) }}

    steps:
      - uses: actions/checkout@v2

      # - name: Install tps
      #   run: |
      #     git clone --depth 1 https://github.com/ioi-2017/tps.git
      #     cd tps && sudo ./install-tps.sh
      - name: env
        env:
          NEEDS: ${{ toJson(needs) }}
        run: |
          echo "$NEEDS"

      - name: Build pdf
        working-directory: ${{ matrix.problem }}
        run: |
          echo "Building ${{ matrix.problem }}"

  build-tests:
    if: needs.check-post.outputs.build-tests != '[]'
    needs: check-post
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        problem: ${{ fromJson(needs.check-post.outputs.build-tests) }}

    steps:
      - uses: actions/checkout@v2

      - name: env
        env:
          NEEDS: ${{ toJson(needs) }}
        run: |
          echo "$NEEDS"

      - name: Build pdf
        working-directory: ${{ matrix.problem }}
        run: |
          echo "Building ${{ matrix.problem }}"

  # verify:
  #   runs-on: ubuntu-18.04

  #   strategy:
  #     matrix:
  #       problem: [pA, pB, pC]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install tps
  #       run: |
  #         git clone --depth 1 https://github.com/ioi-2017/tps.git
  #         cd tps && sudo ./install-tps.sh

  #     - name: Verify ${{ matrix.problem }}
  #       working-directory: ${{ matrix.problem }}
  #       run: |
  #         tps verify
